name: snowpark-de-ml
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - pandas=1.5.3
  - notebook=7.0.6
  - scikit-learn=1.3.0
  - cachetools=4.2.2
  - snowflake-snowpark-python[pandas]=1.11.1
  - streamlit==1.26.0
  - boto3
  - pip
  - pip:
    - snowflake-ml-python==1.2.2
    - snowflake==0.6.0
